name: Build .NET Projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:    # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # Or windows-latest if you prefer to use Windows for compilation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the code to the runner

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'  # Use the version that matches your project setup

      - name: Restore dependencies
        run: |
          # Find all .csproj or .sln files and restore dependencies for each one
          for proj in $(find . -name "*.csproj" -or -name "*.sln"); do
            echo "Restoring dependencies for $proj"
            dotnet restore $proj
          done
      - name: Build all projects
        run: |
          # Find all .csproj files and build each one
          for proj in $(find . -name "*.csproj"); do
            echo "Building $proj"
            dotnet build $proj --configuration Release
          done
