name: Sync Private to Public

on:
  schedule:
    - cron: "0 7 * * 0"  # Every Sunday at 08:00 CET
  workflow_dispatch:      # Allows manual triggering

permissions:
  contents: write          # Grants write permissions to push changes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone the private repository with authentication
      - name: Clone the private repository
        run: |
          rm -rf 1BHIF-Pose-Private  # Remove the existing clone if it exists
          git clone https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/lukasWastaken/1BHIF-Pose-Private.git  # Use token in the URL for authentication
          cd 1BHIF-Pose-Private  # Change into the directory after cloning
          git remote add public https://github.com/lukasWastaken/1BHIF-Pose.git  # Add the public repository as a remote

      # Step 2: Push everything (branches, tags, commits) to the public repository
      - name: Push to the public repository
        run: |
          cd 1BHIF-Pose-Private  # Make sure to be in the right directory
          git push --mirror https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/lukasWastaken/1BHIF-Pose.git  # Push to the public repository using the token for authentication
