name: Sync Private to Public

on:
  schedule:
    - cron: "0 7 * * 0"  # Every Sunday at 08:00 CET
  workflow_dispatch:      # Allows manual triggering

permissions:
  contents: write          # Grants write permissions to push changes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone the private repository with authentication
      - name: Clone the private repository
        run: |
          rm -rf 1BHIF-Pose-Private  # Remove the existing clone if it exists
          git clone https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/lukasWastaken/1BHIF-Pose-Private.git  # Use token in the URL for authentication
          cd 1BHIF-Pose-Private  # Change into the directory after cloning
          git remote add public https://github.com/lukasWastaken/1BHIF-Pose.git  # Add the public repository as a remote

      # Step 2: Set Git user name and email
      - name: Set Git user
        run: |
          git config --global user.email "l.leutgeb@students.htl-leonding.ac.at"  # Set the email for commits
          git config --global user.name "GitHub Actions"  # Set the username for commits

      # Step 3: Remove the .github folder and ensure it is ignored
      - name: Remove and ignore .github folder
        run: |
          cd 1BHIF-Pose-Private  # Change into the directory
          rm -rf .github  # Remove the .github folder
          echo '.github/' >> .gitignore  # Add .github/ to .gitignore temporarily
          git add .gitignore  # Add the .gitignore change
          git commit -m "Temporarily ignore .github folder"

      # Step 4: Push to the public repository
      - name: Push to the public repository
        run: |
          cd 1BHIF-Pose-Private  # Make sure to be in the right directory
          git push https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/lukasWastaken/1BHIF-Pose.git main --no-verify  # Push only the main branch to the public repository using the token for authentication
