name: Sync Private to Public

on:
    schedule:
      - cron: "0 7 * * 0"  # Every Sunday at 08:00 CET
    workflow_dispatch:     # Allows manual triggering
  
  

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the private repository
        uses: actions/checkout@v3

      - name: Add the public repository as a remote
        run: git remote add public https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/lukasWastaken/1BHIF-Pose
      

      - name: Push to public repository
        run: |
          git push -u public main -f
